# Generated by Django 3.1.4 on 2020-12-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0002_auto_20201231_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(max_length=255, verbose_name='Caption')),
                ('portfolio_img', models.ImageField(upload_to='Portfolioimages/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name_plural': 'Blog Images'},
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sitemanager.blogs', verbose_name='Blog Title'),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog_images',
            field=models.ImageField(upload_to='blogimages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_desc',
            field=models.TextField(max_length=20000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_img',
            field=models.ImageField(upload_to='blogimages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
