# Generated by Django 3.1.4 on 2021-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0004_mapsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsection',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='mapsection',
            name='address_url',
            field=models.URLField(max_length=10000, verbose_name='Address Url'),
        ),
        migrations.AlterField(
            model_name='mapsection',
            name='avl_time',
            field=models.CharField(max_length=255, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='mapsection',
            name='contact_no',
            field=models.CharField(max_length=255, verbose_name='Contact Number'),
        ),
    ]
