# Generated by Django 3.1.4 on 2021-01-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0005_auto_20210101_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsection',
            name='address_url',
            field=models.SlugField(max_length=10000, verbose_name='Address Url'),
        ),
    ]
