# Generated by Django 3.1.4 on 2021-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0006_auto_20210101_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsection',
            name='address_url',
            field=models.TextField(verbose_name='Address Url'),
        ),
    ]
