# Generated by Django 3.1 on 2021-01-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0007_auto_20210101_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsection',
            name='avl_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Time'),
        ),
    ]
