# Generated by Django 3.1.4 on 2021-01-03 11:49

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0008_auto_20210101_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blod_pubdate',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, verbose_name='Published Date & Time'),
        ),
    ]
