# Generated by Django 3.1.4 on 2021-01-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0009_blogs_blod_pubdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blod_pubdate',
            new_name='blog_pubdate',
        ),
    ]
