# Generated by Django 3.1.4 on 2021-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0010_auto_20210103_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_published',
            field=models.BooleanField(default=True, verbose_name='Published Status'),
        ),
    ]
