# Generated by Django 3.1.4 on 2021-01-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0013_auto_20210103_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_published',
            new_name='blog_publish',
        ),
    ]
