# Generated by Django 3.1.4 on 2021-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0014_auto_20210103_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimages',
            name='publish_status',
            field=models.BooleanField(default=True, verbose_name='Publish Status'),
        ),
    ]
