# Generated by Django 3.1.4 on 2021-01-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0015_portfolioimages_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimages',
            name='publish_status',
            field=models.BooleanField(verbose_name='Publish Status'),
        ),
    ]
