# Generated by Django 3.1.4 on 2021-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0016_auto_20210103_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('personal_contactno', models.CharField(max_length=255, verbose_name='Contact No')),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
    ]
