# Generated by Django 3.1.4 on 2021-01-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0017_auto_20210103_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_caption', models.CharField(max_length=255, verbose_name='Caption')),
                ('blog_image', models.ImageField(upload_to='blogdescimages/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Blog Description Images',
            },
        ),
    ]
