# Generated by Django 3.1.4 on 2021-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0019_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image_src',
            field=models.ImageField(upload_to='Profileimage/', verbose_name='Image size(600x500px)'),
        ),
    ]
