# Generated by Django 3.1 on 2021-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanager', '0020_auto_20210104_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carouse_caption', models.CharField(max_length=255, verbose_name='Title')),
                ('cimage_src', models.ImageField(upload_to='Carouselimages/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
